# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-11 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlemail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='urls',
            field=models.URLField(max_length=250),
        ),
    ]
