# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-11 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlemail', '0002_auto_20190811_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='urls',
            field=models.URLField(max_length=1000),
        ),
    ]
