# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-11 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlemail', '0004_auto_20190811_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='urls',
            field=models.TextField(max_length=1000),
        ),
    ]
